steps:
  - name: "gcr.io/cloud-builders/go:debian"
    args: ["install", "https_test"]
  - name: "gcr.io/cloud-builders/go:debian"
    args: ["test", "https_test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/https_test:debian", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "gcr.io/$PROJECT_ID/https_test:debian"]

images: ["gcr.io/$PROJECT_ID/https_test:debian"]
